{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "games-platform.fullname" . }}
  {{- if .Values.monitoring.namespace }}
  namespace: {{ .Values.monitoring.namespace }}
  {{- end }}
  labels:
    {{- include "games-platform.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "games-platform.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.monitoring.scrapeInterval }}
{{- end }}