scrape_configs:
  - job_name: games-platform-api
    scheme: https
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s
    static_configs:
      - targets:
          - api.example.com       # prod
          - staging.api.example.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: env
        replacement: prod
        regex: api\.example\.com
      - source_labels: [__address__]
        target_label: env
        replacement: staging
        regex: staging\.api\.example\.com
